#      --[ Craft Slot Commands 4 ]--

# Enter the command to register in the crafting slots
# 제작 공간에 등록할 명령어를 입력합니다

# --------------------------------------#
# If you put * in the start of a command
# it will be executed by the console

# 명령어 앞에 * 를 붙이면 플레이어가 아닌 서버에서 처리합니다
# Example - "*say Hello World" == CONSOLE - "HELLO WORLD"

# PAPI SUPPORT
# PAPI 지원
# --------------------------------------#

# crafting-slot or keybind-commands
cmd-type: crafting-slot

crafting-slot:
  # Crafting result slot
  0: "A"
  # Top left slot
  1: "B"
  # Top right slot
  2: "C"
  # Bottom left slot
  3: "D"
  # Bottom right slot
  4: "E"
  
# Set whether to place custom items in the crafting slots
# If you want to use it, change it to true

# 제작 공간에 커스텀 아이템을 배치할 것인지 설정합니다
# 사용하고 싶다면 true 로 바꿔주세요

items-enabled: true

# Setting up items to use in your crafting slots
# 제작 공간에 사용할 메뉴 아이템을 설정합니다

# --------------------------------------#
# model - CustomModelData / damage - Durability / hide-flags - Hide Flags / lore - Lore
# skull-owner-uuid - Player Head Item Type 1 Value
# skull-texture-value - Player Head Item Type 2 Value

# 0 - Result slot / 제작 결과물 공간
# 1 - Top + Left / 왼쪽 + 위쪽 공간
# 2 - Top + Right / 오른쪽 + 위쪽 공간
# 3 - Bottom + Left / 왼쪽 + 아래쪽 공간
# 4 - Bottom + Right / 오른쪽 + 아래쪽 공간

slot-item:
  0:
    material: DIRT
    name: "&6A"
  1:
    material: SAND
    name: "&6B"
  2:
    material: STONE
    name: "&6C"
  3:
    material: SANDSTONE
    name: "&6D"
  4:
    material: END_STONE
    name: "&6E"

# Set the slot to use
# True to enable, false to disable
# Slots set to false are not used

# 사용할 슬롯을 설정합니다
# true 로 활성화 false 로 비활성화 입니다
# false 가 된 슬롯은 사용되지 않습니다

use-slot:
  # Crafting result slot
  0: true
  # Top left slot
  1: true
  # Top right slot
  2: true
  # Bottom left slot
  3: true
  # Bottom right slot
  4: true

keybind-commands:
  0:
    1: "/say Pressed 1 on slot 0"
    2: "/say Pressed 2 on slot 0"
    3: "/say Pressed 3 on slot 0"
    4: "/say Pressed 4 on slot 0"
    5: "/say Pressed 5 on slot 0"
    6: "/say Pressed 6 on slot 0"
    7: "/say Pressed 7 on slot 0"
    8: "/say Pressed 8 on slot 0"
    9: "/say Pressed 9 on slot 0"
    Q: "/say You pressed Q on slot 0"
    F: "/say Swapped hand in slot 0"
    LEFT: "/say Left click slot 0"
    RIGHT: "/say Right click slot 0"
    DROP: "/say Dropped item from slot 0"

  1:
    1: "/say Pressed 1 on slot 1"
    2: "/say Pressed 2 on slot 1"
    3: "/say Pressed 3 on slot 1"
    4: "/say Pressed 4 on slot 1"
    5: "/say Pressed 5 on slot 1"
    6: "/say Pressed 6 on slot 1"
    7: "/say Pressed 7 on slot 1"
    8: "/say Pressed 8 on slot 1"
    9: "/say Pressed 9 on slot 1"
    Q: "/say You pressed Q on slot 1"
    F: "/say Swapped hand in slot 1"
    LEFT: "/say Left click slot 1"
    RIGHT: "/say Right click slot 1"
    DROP: "/say Dropped item from slot 1"

  2:
    1: "/say Pressed 1 on slot 2"
    2: "/say Pressed 2 on slot 2"
    3: "/say Pressed 3 on slot 2"
    4: "/say Pressed 4 on slot 2"
    5: "/say Pressed 5 on slot 2"
    6: "/say Pressed 6 on slot 2"
    7: "/say Pressed 7 on slot 2"
    8: "/say Pressed 8 on slot 2"
    9: "/say Pressed 9 on slot 2"
    Q: "/say You pressed Q on slot 2"
    F: "/say Swapped hand in slot 2"
    LEFT: "/say Left click slot 2"
    RIGHT: "/say Right click slot 2"
    DROP: "/say Dropped item from slot 2"

  3:
    1: "/say Pressed 1 on slot 3"
    2: "/say Pressed 2 on slot 3"
    3: "/say Pressed 3 on slot 3"
    4: "/say Pressed 4 on slot 3"
    5: "/say Pressed 5 on slot 3"
    6: "/say Pressed 6 on slot 3"
    7: "/say Pressed 7 on slot 3"
    8: "/say Pressed 8 on slot 3"
    9: "/say Pressed 9 on slot 3"
    Q: "/say You pressed Q on slot 3"
    F: "/say Swapped hand in slot 3"
    LEFT: "/say Left click slot 3"
    RIGHT: "/say Right click slot 3"
    DROP: "/say Dropped item from slot 3"

  4:
    1: "/say Pressed 1 on slot 4"
    2: "/say Pressed 2 on slot 4"
    3: "/say Pressed 3 on slot 4"
    4: "/say Pressed 4 on slot 4"
    5: "/say Pressed 5 on slot 4"
    6: "/say Pressed 6 on slot 4"
    7: "/say Pressed 7 on slot 4"
    8: "/say Pressed 8 on slot 4"
    9: "/say Pressed 9 on slot 4"
    Q: "/say You pressed Q on slot 4"
    F: "/say Swapped hand in slot 4"
    LEFT: "/say Left click slot 4"
    RIGHT: "/say Right click slot 4"
    DROP: "/say Dropped item from slot 4"
